### ISSUE TITLE
Table name should be configurable

### ISSUE THREAD

**Issue by niosocket** [pj4533/PokerNowGrabber#3]
PokerTracker will confuse different stakes if played on the table with the same name which will happen if somebody using this software with different stakes.

Should be configurable through the form.

**Comment by pj4533** [comment]
Made a change to name the table as the PokerNow game id.   This should fix most cases of this issue.   I think the only one that analysis software might have an issue with is when the stakes on a single table change mid-session.   Not sure what to do there...

I don't like the idea of yet another configurable option, but maybe it is required?   Maybe have the table name default to the game ID, but you can change it if you want?
