### ISSUE TITLE
Ability to process log files

### ISSUE THREAD

**Issue by simons-plugins** [pj4533/PokerNowGrabber#6]
Not sure how you are capturing what is happening to convert into the pokerstars format, but if its like the way that pokernow stores its logs, would it be possible to run this against log files we have downloaded?  It would be great to be able to process my last 6 months of weekly games to get an instant history.  
Thanks

**Comment by pj4533** [comment]
Sure, if you are on a Mac, you can use this project to bulk process them all:  https://github.com/pj4533/pn2ps

If not on a Mac (or don't like CLI programs), you can use this website to do them one at a time: http://pokernowconvert.herokuapp.com

All three use the same shared codebase to do the conversion, which is open sourced here: https://github.com/pj4533/PokerNowKit
